# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: esp_rmaker_user_mapping.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'esp_rmaker_user_mapping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65sp_rmaker_user_mapping.proto\x12\trainmaker\"6\n\x11\x43mdSetUserMapping\x12\x0e\n\x06UserID\x18\x01 \x01(\t\x12\x11\n\tSecretKey\x18\x02 \x01(\t\"S\n\x12RespSetUserMapping\x12-\n\x06Status\x18\x01 \x01(\x0e\x32\x1d.rainmaker.RMakerConfigStatus\x12\x0e\n\x06NodeId\x18\x02 \x01(\t\"\xcb\x01\n\x13RMakerConfigPayload\x12+\n\x03msg\x18\x01 \x01(\x0e\x32\x1e.rainmaker.RMakerConfigMsgType\x12<\n\x14\x63md_set_user_mapping\x18\n \x01(\x0b\x32\x1c.rainmaker.CmdSetUserMappingH\x00\x12>\n\x15resp_set_user_mapping\x18\x0b \x01(\x0b\x32\x1d.rainmaker.RespSetUserMappingH\x00\x42\t\n\x07payload*E\n\x12RMakerConfigStatus\x12\x0b\n\x07Success\x10\x00\x12\x10\n\x0cInvalidParam\x10\x01\x12\x10\n\x0cInvalidState\x10\x02*L\n\x13RMakerConfigMsgType\x12\x19\n\x15TypeCmdSetUserMapping\x10\x00\x12\x1a\n\x16TypeRespSetUserMapping\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'esp_rmaker_user_mapping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RMAKERCONFIGSTATUS']._serialized_start=391
  _globals['_RMAKERCONFIGSTATUS']._serialized_end=460
  _globals['_RMAKERCONFIGMSGTYPE']._serialized_start=462
  _globals['_RMAKERCONFIGMSGTYPE']._serialized_end=538
  _globals['_CMDSETUSERMAPPING']._serialized_start=44
  _globals['_CMDSETUSERMAPPING']._serialized_end=98
  _globals['_RESPSETUSERMAPPING']._serialized_start=100
  _globals['_RESPSETUSERMAPPING']._serialized_end=183
  _globals['_RMAKERCONFIGPAYLOAD']._serialized_start=186
  _globals['_RMAKERCONFIGPAYLOAD']._serialized_end=389
# @@protoc_insertion_point(module_scope)
