# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: esp_rmaker_claim.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'esp_rmaker_claim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65sp_rmaker_claim.proto\x12\x0crmaker_claim\"?\n\nPayloadBuf\x12\x0e\n\x06Offset\x18\x01 \x01(\r\x12\x0f\n\x07Payload\x18\x02 \x01(\x0c\x12\x10\n\x08TotalLen\x18\x03 \x01(\r\"e\n\x0bRespPayload\x12/\n\x06Status\x18\x01 \x01(\x0e\x32\x1f.rmaker_claim.RMakerClaimStatus\x12%\n\x03\x42uf\x18\x02 \x01(\x0b\x32\x18.rmaker_claim.PayloadBuf\"\xb0\x01\n\x12RMakerClaimPayload\x12-\n\x03msg\x18\x01 \x01(\x0e\x32 .rmaker_claim.RMakerClaimMsgType\x12.\n\ncmdPayload\x18\n \x01(\x0b\x32\x18.rmaker_claim.PayloadBufH\x00\x12\x30\n\x0brespPayload\x18\x0b \x01(\x0b\x32\x19.rmaker_claim.RespPayloadH\x00\x42\t\n\x07payload*\\\n\x11RMakerClaimStatus\x12\x0b\n\x07Success\x10\x00\x12\x08\n\x04\x46\x61il\x10\x01\x12\x10\n\x0cInvalidParam\x10\x02\x12\x10\n\x0cInvalidState\x10\x03\x12\x0c\n\x08NoMemory\x10\x04*\xd0\x01\n\x12RMakerClaimMsgType\x12\x15\n\x11TypeCmdClaimStart\x10\x00\x12\x16\n\x12TypeRespClaimStart\x10\x01\x12\x14\n\x10TypeCmdClaimInit\x10\x02\x12\x15\n\x11TypeRespClaimInit\x10\x03\x12\x16\n\x12TypeCmdClaimVerify\x10\x04\x12\x17\n\x13TypeRespClaimVerify\x10\x05\x12\x15\n\x11TypeCmdClaimAbort\x10\x06\x12\x16\n\x12TypeRespClaimAbort\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'esp_rmaker_claim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RMAKERCLAIMSTATUS']._serialized_start=387
  _globals['_RMAKERCLAIMSTATUS']._serialized_end=479
  _globals['_RMAKERCLAIMMSGTYPE']._serialized_start=482
  _globals['_RMAKERCLAIMMSGTYPE']._serialized_end=690
  _globals['_PAYLOADBUF']._serialized_start=40
  _globals['_PAYLOADBUF']._serialized_end=103
  _globals['_RESPPAYLOAD']._serialized_start=105
  _globals['_RESPPAYLOAD']._serialized_end=206
  _globals['_RMAKERCLAIMPAYLOAD']._serialized_start=209
  _globals['_RMAKERCLAIMPAYLOAD']._serialized_end=385
# @@protoc_insertion_point(module_scope)
